config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  resources :tweets do
    member do
      put "like",to:'tweets#vote'
      # put "follow", to: "tweets#follow"
      # put "unfollow", to: "user#downvote"
    end


    # put directs to controller and upvote
  end
  devise_for :users
  root 'pages#feed'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, ProfilePictureUploader
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  acts_as_votable
  validates :message, :length => { :maximum => 146 }
# nandini - sets maximum tweet size to 146 characters
  include SimpleHashtag::Hashtaggable
  hashtaggable_attribute :message
  def score
    self.get_upvotes.size - self.get_downvotes.size
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_one :profile
  acts_as_voter
  # acts_as_followable
  # acts_as_follower
# nandini ->  without acts as voter we get nil error for @user.voted_as_when_voted_for
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception    
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

  def index
    @hashtags = SimpleHashtag::Hashtag.all
  end

  def show
    @hashtag = SimpleHashtag::Hashtag.find_by_name(params[:hashtag])
    @hashtagged = @hashtag.hashtaggables if @hashtag
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def feed
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile,:set_tweets, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new

  # nandini - if current user profile is nil create a new profile else redirect to the created profile
  def new
    if current_user.profile.nil?
      @profile = Profile.new
    else
      redirect_to profile_path(current_user.profile.id)
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    # nandini - associate user id to profile when created

    @profile.user_id = current_user.id if current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end


# nandini - show all tweets that owner of current profile has

    def set_tweets
      @tweets = Tweet.where(user_id:(Profile.find(params[:id]).user_id))
      # @tweets = Tweet.where(user_id:(current_user.profile.user_id))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:bio, :user_id, :picture)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy,:vote]

  # GET /tweets
  # GET /tweets.json

  def vote
    case current_user.voted_as_when_voted_for(@tweet)
      when nil
        @tweet.upvote_by current_user
      when true
        @tweet.unvote_by current_user
        # unvote removes the vote downvote decreases the score--> nandini
      when false
        @tweet.upvote_by current_user
    else

    end

    redirect_to tweets_path
    # method upvote_by and current_user passed as parameter
    # @tweet.upvote_by(current_user)
  end

  # def nandini(word)
  #   puts "Nadnini is word"
  # end
  #
  # nandini("best")

  # def follow
  #   @user = User.find(params[:id])
  #   current_user.follow(@user)
  # end

  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

  # Set tweet user id to current user -> modified by nandini ->
  # without if current_user: user_id will be assigned when user
  # not logged in and that results in nil entry
    @tweet.user_id = current_user.id if current_user

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
  def linkify_hashtags(hashtaggable_content)
    regex = SimpleHashtag::Hashtag::HASHTAG_REGEX
    hashtagged_content = hashtaggable_content.to_s.gsub(regex) do
      link_to($&, hashtag_path($2), {class: :hashtag})
    end
    hashtagged_content.html_safe
  end

  def render_hashtaggable(hashtaggable)
    klass        = hashtaggable.class.to_s.underscore
    view_dirname = klass.pluralize
    partial      = klass
    render "#{view_dirname}/#{partial}", {klass.to_sym => hashtaggable}
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hashtags/index.html.erb
<h1>Hashtags</h1>
<ul>
<% @hashtags.each do |hashtag| %>
  <li><%= link_to hashtag.name, hashtag_path(hashtag.name) %></li>
<% end -%>
</ul>

app/views/hashtags/show.html.erb
<h1><%= params[:hashtag] %></h1>
<% if @hashtagged %>
  <% @hashtagged.each do |hashtagged| %>
    <%= render_hashtaggable hashtagged %>
  <% end -%>
<% else -%>
  <p>There is no match for the <em><%= params[:hashtag] %></em> hashtag.</p>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/feed.html.erb
<h1>Pages#feed</h1>
<p>Find me in app/views/pages/feed.html.erb</p>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- changes made  by Nandini -->

      <%= link_to "Twitter", root_path, class:"navbar-brand"%>
    </div>
      <!-- changes made  by Nandini -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

          </ul>
        </li>
      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">

        <!-- if statement to produce approriate link depending on user sign in -->
          <% if user_signed_in? %>
          <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          </li>
          <li>
            <%= link_to('Edit registration', edit_user_registration_path) %>
          </li>
          <li>
      
            <%= link_to "Tweets",tweets_path%>
          </li>
          <% else %>
          <li>
            <%= link_to('Login', new_user_session_path)  %>
          </li>
          <li>
             <%= link_to('Register', new_user_registration_path)  %>
           </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>

app/views/profiles/_form.html.erb
<%= simple_form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="form-inputs">
    <li>upload picture</li>
    <%=f.input :picture, as: :file%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Bio</th>
      <th>User</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= image_tag(profile.picture_url) %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.user.email %></td>

        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>
<p>
  <strong>profile picture:</strong>
  <%= image_tag(@profile.picture_url) %>
</p>

<%= @tweets.each do |tweet|%>
  <%=tweet.message%>
<%end%>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<%=tweet.message%>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="4"></th>

      <!-- change 3 to 4 to add extra column which we just created by adding uppvote link->nandini -->
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= linkify_hashtags(tweet.message) %></td>
        <td><%=tweet.user_id%><td>
        <td><%= tweet.user.email %></td>
        <!-- <td><!-%= link_to "follow", follow_tweet_path(tweet.user_id),method: :put%></td> -->
        <td>
          <% if current_user %>
           <%= link_to like_tweet_path(tweet), method: :put do%>
             <%= current_user.voted_as_when_voted_for(tweet) == true ? icon("heart") : icon("heart-o") %>
           <% end %>
           <% else %>
           <%= icon("heart-o") %>
           <% end %>
        </td>
        <td><%=tweet.score%>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= linkify_hashtags(@tweet.message) %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user.email %>
  <!-- <%= @tweet.user.methods %> -->
  <!-- helps you inspect the database -> nandini -->
  <!-- <%= @tweet.user.inspect %> -->
  <!-- lists out the methods -->
  <!-- <%=10.to_s.to_f * 3%> -->
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>